# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Knowledge Discovery
#email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Research focus of the Technische Hochschule Köln
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
plugins:
  - jekyll-feed
  - jekyll-remote-theme

# Default-Theme "Primer" is automatically added by GitHub Pages when no theme has been
# defined using the "theme" key even when a remote theme is set. To prevent confusing logs 
# in development (as the used theme is logged in the terminal), theme is set null here.

#theme: bulma-clean-theme
remote_theme: "chrisrhymes/bulma-clean-theme"

# Defining front matter defaults. This provides default values for front matters and prevents 
# having to manually set, for example, a layout on every file. Empty front matters must still
# be given on pages that should be processed by Jekyll and output in the _site directory.

# Front matter defaults can override one another by specifity of the path given and page types.

defaults:
  -
    scope:
      path: ""
      types: "pages"
    values:
      show_sidebar: true # Enabling a sidebar on all files of type "pages" (not posts or collections)
  -
    scope:
      path: "index.markdown"
    values:
      show_sidebar: false # Disabling sidebar on page "Home"
  -
    scope:
      path: "404.html"
    values:
      show_sidebar: false # Disabling sidebar on page "404"
  -
    scope:
      path: ""
    values:
      layout: "custom_default" # Setting a default layout to all pages
  -
    scope:
      path: ""
      type: "people"
    values:
      layout: "person2"
      show_back_button: true
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "project2"
      show_back_button: true

# Adding collections. Collections provide an easy to set up an architecture for group related
# content, such as members of a group or talks at a conference. New entries to a collection
# can be given by creating a new file in the directory the collection is stored in and providing
# data in the frot matter.
# output needs to be set to true so collection pages are rendered. output is set to false by
# default.
# Collection "news" refers so short news displayed on page "home".
# A permalink is set to manage the output path of collection item output pages.

collections:
  people:
    output: true
    permalink: "/about-us/:collection/:name:output_ext"
  projects:
    output: true
    permalink: "/research/:collection/:name:output_ext"
  publications:
    output: true
    permalink: "/research/:collection/:name:output_ext"
  bsc-msc-theses:
    output: true
    permalink: "/theses-and-jobs/:collection/:name:output_ext"
  news:
    output: false

excerpt_separator: "<!--more-->"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
